### ISSUE TITLE
Badge Alura Challenge

### ISSUE THREAD

**Issue by LucasdeFreitasp** [mdorrocha/alura-challenge-bi#1]
Olá, cientista!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nesse primeiro Challenge de BI da Alura.

Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅

Abraços e te vejo nos próximos Challenge.
![Badge_Alura_Challenge_BI_Sharer](https://user-images.githubusercontent.com/79534537/160188928-41a29231-7d6a-4db9-a30d-e7fd9aac5312.png)

**Comment by mdorrocha** [comment]
Foi muito bom participar do challenge. Fico aguardando os próximos.
Obrigado!
